// lang.js - 8 языков для Chain Bank
const translations = {
    en: {
        title: "Chain Bank", motto: "In God We Trust", candles: "Candles", charity: "Charity",
        buy_tokens: "Buy tokens", dao: "DAO", memory: "Memory Book",
        quote: "Faith without works is dead — light a candle, help your neighbor, gain eternal memory.",
        yourWallet: "Your data for recording", wallet_placeholder: "Your Solana wallet", name_placeholder: "Your name",
        save: "✙ Save", saved: "Saved", copied: "Copied!", need_wallet: "Enter wallet", need_txid: "Enter TXID",
        send_vbdc_desc: "Send 1 VBDC to DEUS address. Paste TXID:",
        send_deus_desc: "Send 1 DEUS to DIABOLUS address. Paste TXID:",
        send_eternal_desc: "Send 1 VBST + 1 VBDC to DEUS address. Paste TXID:",
        verify_title: "Confirmation", txid_placeholder: "Paste TXID (transaction hash)", verify_btn: "✙ Verify",
        donate_direct: "Direct donations (SOL / USDC)", copy: "📋 Copy", swap_title: "Buy tokens via swap",
        onramp_title: "Buy SOL/USDC with card", swift_title: "Large donations (SWIFT / SEPA)",
        swift_desc: "For donations from $1000. After transfer, contact us:",
        swift_note: "📌 After transfer, send confirmation and your wallet — we will credit tokens manually.",
        refer_title: "Refer a friend", footer: "Faith, hope, love and blockchain",
        against_btn: "💀 Against God", eternal_btn: "✨ Eternal Candle", for_btn: "📿 For God",
        forGod: "For God", againstGod: "Against God", candles_count: "Candles burning"
    },
    ru: {
        title: "Chain Bank", motto: "In God We Trust", candles: "Свечи", charity: "Благотворительность",
        buy_tokens: "Купить токены", dao: "DAO", memory: "Книга памяти",
        quote: "«Вера без дел мертва» — зажгите свечу, помогите ближнему, обретите вечную память.",
        yourWallet: "Ваши данные для записи", wallet_placeholder: "Ваш Solana кошелёк", name_placeholder: "Ваше имя",
        save: "✙ Сохранить", saved: "Сохранено", copied: "Скопировано!", need_wallet: "Введите кошелёк", need_txid: "Введите TXID",
        send_vbdc_desc: "Отправьте 1 VBDC на адрес DEUS. Вставьте TXID:",
        send_deus_desc: "Отправьте 1 DEUS на адрес DIABOLUS. Вставьте TXID:",
        send_eternal_desc: "Отправьте 1 VBST + 1 VBDC на адрес DEUS. Вставьте TXID:",
        verify_title: "Подтверждение", txid_placeholder: "Вставьте TXID (хеш транзакции)", verify_btn: "✙ Проверить",
        donate_direct: "Прямые пожертвования (SOL / USDC)", copy: "📋 Копировать", swap_title: "Купить токены через своп",
        onramp_title: "Купить SOL/USDC с карты", swift_title: "Крупные пожертвования (SWIFT / SEPA)",
        swift_desc: "Для пожертвований от $1000. После перевода свяжитесь с нами:",
        swift_note: "📌 После перевода отправьте подтверждение и ваш кошелёк — мы зачислим токены вручную.",
        refer_title: "Приведи друга", footer: "Вера, надежда, любовь и блокчейн",
        against_btn: "💀 Против Бога", eternal_btn: "✨ Вечная свеча", for_btn: "📿 За Бога",
        forGod: "За Бога", againstGod: "Против Бога", candles_count: "Свечей горит"
    },
    es: { title: "Chain Bank", motto: "In God We Trust", candles: "Velas", charity: "Caridad", buy_tokens: "Comprar tokens", dao: "DAO", memory: "Libro de memoria", quote: "La fe sin obras está muerta — enciende una vela, ayuda a tu prójimo, obtén memoria eterna.", yourWallet: "Tus datos", wallet_placeholder: "Tu wallet Solana", name_placeholder: "Tu nombre", save: "✙ Guardar", saved: "Guardado", copied: "¡Copiado!", need_wallet: "Ingrese wallet", need_txid: "Ingrese TXID", send_vbdc_desc: "Envíe 1 VBDC a DEUS. Pegue TXID:", send_deus_desc: "Envíe 1 DEUS a DIABOLUS. Pegue TXID:", send_eternal_desc: "Envíe 1 VBST + 1 VBDC a DEUS. Pegue TXID:", verify_title: "Confirmación", txid_placeholder: "Pegue TXID", verify_btn: "✙ Verificar", donate_direct: "Donaciones directas (SOL/USDC)", copy: "📋 Copiar", swap_title: "Comprar tokens vía swap", onramp_title: "Comprar SOL/USDC con tarjeta", swift_title: "Donaciones grandes (SWIFT/SEPA)", swift_desc: "Para donaciones desde $1000. Después de transferir, contáctenos:", swift_note: "📌 Envíe confirmación y su wallet — acreditaremos tokens manualmente.", refer_title: "Recomendar amigo", footer: "Fe, esperanza, amor y blockchain", against_btn: "💀 Contra Dios", eternal_btn: "✨ Vela eterna", for_btn: "📿 Para Dios", forGod: "Para Dios", againstGod: "Contra Dios", candles_count: "Velas encendidas" },
    // Добавьте остальные языки (zh, fr, de, it, ja) по аналогии с ru или en
    zh: { title: "Chain Bank", motto: "In God We Trust", candles: "蜡烛", charity: "慈善", buy_tokens: "购买代币", dao: "DAO", memory: "记忆之书", quote: "没有行为的信心是死的——点燃蜡烛，帮助邻舍，获得永恒的记忆。", yourWallet: "您的数据", wallet_placeholder: "您的Solana钱包", name_placeholder: "您的名字", save: "✙ 保存", saved: "已保存", copied: "已复制！", need_wallet: "输入钱包", need_txid: "输入TXID", send_vbdc_desc: "发送1 VBDC到DEUS地址。粘贴TXID：", send_deus_desc: "发送1 DEUS到DIABOLUS地址。粘贴TXID：", send_eternal_desc: "发送1 VBST + 1 VBDC到DEUS地址。粘贴TXID：", verify_title: "确认", txid_placeholder: "粘贴TXID", verify_btn: "✙ 验证", donate_direct: "直接捐赠 (SOL/USDC)", copy: "📋 复制", swap_title: "通过交换购买代币", onramp_title: "用卡购买SOL/USDC", swift_title: "大额捐赠 (SWIFT/SEPA)", swift_desc: "捐赠$1000起。转账后联系我们：", swift_note: "📌 转账后发送确认信息和您的钱包——我们将手动记入代币。", refer_title: "推荐朋友", footer: "信仰、希望、爱与区块链", against_btn: "💀 对抗上帝", eternal_btn: "✨ 永恒蜡烛", for_btn: "📿 为了上帝", forGod: "为了上帝", againstGod: "对抗上帝", candles_count: "点燃的蜡烛" },
    fr: { title: "Chain Bank", motto: "In God We Trust", candles: "Bougies", charity: "Charité", buy_tokens: "Acheter des tokens", dao: "DAO", memory: "Livre de mémoire", quote: "La foi sans les œuvres est morte — allumez une bougie, aidez votre prochain, obtenez la mémoire éternelle.", yourWallet: "Vos données", wallet_placeholder: "Votre portefeuille Solana", name_placeholder: "Votre nom", save: "✙ Sauvegarder", saved: "Sauvegardé", copied: "Copié !", need_wallet: "Entrez le portefeuille", need_txid: "Entrez TXID", send_vbdc_desc: "Envoyez 1 VBDC à DEUS. Collez TXID :", send_deus_desc: "Envoyez 1 DEUS à DIABOLUS. Collez TXID :", send_eternal_desc: "Envoyez 1 VBST + 1 VBDC à DEUS. Collez TXID :", verify_title: "Confirmation", txid_placeholder: "Collez TXID", verify_btn: "✙ Vérifier", donate_direct: "Dons directs (SOL/USDC)", copy: "📋 Copier", swap_title: "Acheter des tokens via swap", onramp_title: "Acheter SOL/USDC par carte", swift_title: "Dons importants (SWIFT/SEPA)", swift_desc: "Pour les dons à partir de $1000. Après le transfert, contactez-nous :", swift_note: "📌 Après le transfert, envoyez la confirmation et votre portefeuille — nous créditerons les tokens manuellement.", refer_title: "Parrainer un ami", footer: "Foi, espérance, amour et blockchain", against_btn: "💀 Contre Dieu", eternal_btn: "✨ Bougie éternelle", for_btn: "📿 Pour Dieu", forGod: "Pour Dieu", againstGod: "Contre Dieu", candles_count: "Bougies allumées" },
    de: { title: "Chain Bank", motto: "In God We Trust", candles: "Kerzen", charity: "Wohltätigkeit", buy_tokens: "Token kaufen", dao: "DAO", memory: "Gedenkbuch", quote: "Der Glaube ohne Werke ist tot — zünde eine Kerze an, hilf deinem Nächsten, erlange ewige Erinnerung.", yourWallet: "Ihre Daten", wallet_placeholder: "Ihre Solana Wallet", name_placeholder: "Ihr Name", save: "✙ Speichern", saved: "Gespeichert", copied: "Kopiert!", need_wallet: "Wallet eingeben", need_txid: "TXID eingeben", send_vbdc_desc: "Senden Sie 1 VBDC an DEUS. Fügen Sie TXID ein:", send_deus_desc: "Senden Sie 1 DEUS an DIABOLUS. Fügen Sie TXID ein:", send_eternal_desc: "Senden Sie 1 VBST + 1 VBDC an DEUS. Fügen Sie TXID ein:", verify_title: "Bestätigung", txid_placeholder: "TXID einfügen", verify_btn: "✙ Prüfen", donate_direct: "Direkte Spenden (SOL/USDC)", copy: "📋 Kopieren", swap_title: "Token per Swap kaufen", onramp_title: "SOL/USDC mit Karte kaufen", swift_title: "Großspenden (SWIFT/SEPA)", swift_desc: "Für Spenden ab $1000. Nach der Überweisung kontaktieren Sie uns:", swift_note: "📌 Senden Sie die Bestätigung und Ihre Wallet — wir werden die Token manuell gutschreiben.", refer_title: "Freund empfehlen", footer: "Glaube, Hoffnung, Liebe und Blockchain", against_btn: "💀 Gegen Gott", eternal_btn: "✨ Ewige Kerze", for_btn: "📿 Für Gott", forGod: "Für Gott", againstGod: "Gegen Gott", candles_count: "Kerzen brennen" },
    it: { title: "Chain Bank", motto: "In God We Trust", candles: "Candele", charity: "Carità", buy_tokens: "Compra token", dao: "DAO", memory: "Libro della memoria", quote: "La fede senza le opere è morta — accendi una candela, aiuta il prossimo, ottieni la memoria eterna.", yourWallet: "I tuoi dati", wallet_placeholder: "Il tuo portafoglio Solana", name_placeholder: "Il tuo nome", save: "✙ Salva", saved: "Salvato", copied: "Copiato!", need_wallet: "Inserisci wallet", need_txid: "Inserisci TXID", send_vbdc_desc: "Invia 1 VBDC a DEUS. Incolla TXID:", send_deus_desc: "Invia 1 DEUS a DIABOLUS. Incolla TXID:", send_eternal_desc: "Invia 1 VBST + 1 VBDC a DEUS. Incolla TXID:", verify_title: "Conferma", txid_placeholder: "Incolla TXID", verify_btn: "✙ Verifica", donate_direct: "Donazioni dirette (SOL/USDC)", copy: "📋 Copia", swap_title: "Compra token tramite swap", onramp_title: "Compra SOL/USDC con carta", swift_title: "Grandi donazioni (SWIFT/SEPA)", swift_desc: "Per donazioni da $1000. Dopo il trasferimento, contattaci:", swift_note: "📌 Dopo il trasferimento, invia conferma e il tuo wallet — accrediteremo i token manualmente.", refer_title: "Invita un amico", footer: "Fede, speranza, amore e blockchain", against_btn: "💀 Contro Dio", eternal_btn: "✨ Candela eterna", for_btn: "📿 Per Dio", forGod: "Per Dio", againstGod: "Contro Dio", candles_count: "Candele accese" },
    ja: { title: "Chain Bank", motto: "In God We Trust", candles: "キャンドル", charity: "慈善", buy_tokens: "トークンを購入", dao: "DAO", memory: "追悼録", quote: "信仰がなくて行いがないのは死んでいる — キャンドルを灯し、隣人を助け、永遠の記憶を得なさい。", yourWallet: "あなたのデータ", wallet_placeholder: "あなたのSolanaウォレット", name_placeholder: "あなたの名前", save: "✙ 保存", saved: "保存しました", copied: "コピーしました！", need_wallet: "ウォレットを入力", need_txid: "TXIDを入力", send_vbdc_desc: "1 VBDCをDEUSアドレスに送信します。TXIDを貼り付けてください：", send_deus_desc: "1 DEUSをDIABOLUSアドレスに送信します。TXIDを貼り付けてください：", send_eternal_desc: "1 VBST + 1 VBDCをDEUSアドレスに送信します。TXIDを貼り付けてください：", verify_title: "確認", txid_placeholder: "TXIDを貼り付け", verify_btn: "✙ 検証", donate_direct: "直接寄付 (SOL/USDC)", copy: "📋 コピー", swap_title: "スワップでトークンを購入", onramp_title: "カードでSOL/USDCを購入", swift_title: "大口寄付 (SWIFT/SEPA)", swift_desc: "$1000以上の寄付の場合。送金後、お問い合わせください：", swift_note: "📌 送金後、確認とウォレットを送信してください — 手動でトークンを記入します。", refer_title: "友人を紹介", footer: "信仰、希望、愛、そしてブロックチェーン", against_btn: "💀 神に逆らう", eternal_btn: "✨ 永遠のキャンドル", for_btn: "📿 神のために", forGod: "神のために", againstGod: "神に逆らう", candles_count: "燃えているキャンドル" }
};
let currentLang = localStorage.getItem('chainbank_lang') || 'ru';
function setLanguage(lang) { currentLang = lang; localStorage.setItem('chainbank_lang', lang); document.querySelectorAll('[data-i18n]').forEach(el => { const key = el.getAttribute('data-i18n'); if(translations[lang] && translations[lang][key]) { if(el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.placeholder = translations[lang][key]; else el.innerHTML = translations[lang][key]; } }); document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { const key = el.getAttribute('data-i18n-placeholder'); if(translations[lang] && translations[lang][key]) el.placeholder = translations[lang][key]; }); document.querySelectorAll('.lang-btn').forEach(btn => { if(btn.dataset.lang === lang) btn.classList.add('active'); else btn.classList.remove('active'); }); }
function renderLangButtons(containerId='lang-switcher') { const container = document.getElementById(containerId); if(!container) return; const langs = { en:'EN', ru:'RU', es:'ES', zh:'中文', fr:'FR', de:'DE', it:'IT', ja:'JP' }; container.innerHTML = ''; Object.entries(langs).forEach(([code, name]) => { const btn = document.createElement('button'); btn.innerText = name; btn.dataset.lang = code; btn.className = `lang-btn ${currentLang === code ? 'active' : ''} bg-white/10 hover:bg-gold/30 px-2 py-1 rounded-full text-sm transition`; btn.onclick = () => setLanguage(code); container.appendChild(btn); }); }
document.addEventListener('DOMContentLoaded', () => { renderLangButtons(); setLanguage(currentLang); });
