// Добавьте в объект translations.ru (или создайте, если нет)
ru: {
    title: "Chain Bank",
    motto: "In God We Trust",
    candles: "Свечи",
    charity: "Благотворительность",
    buy_tokens: "Купить токены",
    dao: "DAO",
    memory: "Книга памяти",
    quote: "«Вера без дел мертва» — зажгите свечу, помогите ближнему, обретите вечную память.",
    yourWallet: "Ваши данные для записи",
    wallet_placeholder: "Ваш Solana кошелёк",
    name_placeholder: "Ваше имя",
    save: "✙ Сохранить",
    saved: "Сохранено",
    copied: "Скопировано!",
    need_wallet: "Введите кошелёк",
    need_txid: "Введите TXID",
    send_vbdc_desc: "Отправьте 1 VBDC на адрес DEUS. Вставьте TXID:",
    send_deus_desc: "Отправьте 1 DEUS на адрес DIABOLUS. Вставьте TXID:",
    send_eternal_desc: "Отправьте 1 VBST + 1 VBDC на адрес DEUS. Вставьте TXID:",
    verify_title: "Подтверждение",
    txid_placeholder: "Вставьте TXID (хеш транзакции)",
    verify_btn: "✙ Проверить",
    donate_direct: "Прямые пожертвования (SOL / USDC)",
    copy: "📋 Копировать",
    swap_title: "Купить токены через своп",
    onramp_title: "Купить SOL/USDC с карты",
    swift_title: "Крупные пожертвования (SWIFT / SEPA)",
    swift_desc: "Для пожертвований от $1000. После перевода свяжитесь с нами:",
    swift_note: "📌 После перевода отправьте подтверждение и ваш кошелёк — мы зачислим токены вручную.",
    refer_title: "Приведи друга",
    footer: "Вера, надежда, любовь и блокчейн",
    against_btn: "💀 Против Бога",
    eternal_btn: "✨ Вечная свеча",
    for_btn: "📿 За Бога",
    forGod: "За Бога",
    againstGod: "Против Бога"
}
// Аналогично для других языков (en, es, zh, fr, de, it, ja) — переведите эти ключи.
